# thinking1

# thinking2

# thinking3

# action1

In [9]:
import numpy as np
a = np.array(
[
    [0,0,0,1/3,0,0],
    [1/3,0,0,0,1/2,0],
    [0,1,0,1/3,1/2,0],
    [1/3,0,0,0,0,1],
    [0,0,1,1/3,0,0],
    [1/3,0,0,0,0,0]
])
b = np.array([1/6,1/6,1/6,1/6,1/6,1/6])
w = b
def work(a,w):
    for i in range(100):
        w = np.dot(a,w)
        print(w)
def random_work(a,w,n):
    d = 0.85
    for i in range(100):
        w = (1-d)/n+d*np.dot(a,w)
        print(w)

In [10]:
work(a,w)

[0.05555556 0.13888889 0.30555556 0.22222222 0.22222222 0.05555556]
[0.07407407 0.12962963 0.32407407 0.07407407 0.37962963 0.01851852]
[0.02469136 0.21450617 0.3441358  0.04320988 0.34876543 0.02469136]
[0.01440329 0.18261317 0.40329218 0.03292181 0.35853909 0.00823045]
[0.01097394 0.18407064 0.37285665 0.01303155 0.41426612 0.0048011 ]
[0.00434385 0.21079104 0.39554755 0.00845908 0.3772005  0.00365798]
[0.00281969 0.1900482  0.40221098 0.00510593 0.39836725 0.00144795]
[0.00170198 0.20012352 0.3909338  0.00238785 0.40391296 0.0009399 ]
[0.00079595 0.2025238  0.40287595 0.00150722 0.39172975 0.00056733]
[5.02407605e-04 1.96130191e-01 3.98891087e-01 8.32641817e-04
 4.03378356e-01 2.65316376e-04]
[2.77547272e-04 2.01856647e-01 3.98096917e-01 4.32785577e-04
 3.99168634e-01 1.67469202e-04]
[1.44261859e-04 1.99676833e-01 4.01585226e-01 2.59984959e-04
 3.98241178e-01 9.25157575e-05]
[8.66616530e-05 1.99168676e-01 3.98884084e-01 1.40603044e-04
 4.01671888e-01 4.80872864e-05]
[4.68676813e-05 

In [12]:
random_work(a,w,n=4)

[0.08472222 0.15555556 0.29722222 0.22638889 0.22638889 0.08472222]
[0.10164352 0.15771991 0.33008102 0.13351852 0.35428241 0.06150463]
[0.07533025 0.21686902 0.35996219 0.11857793 0.35589911 0.066299  ]
[0.07109708 0.21010069 0.40669287 0.11519772 0.37706494 0.05884357]
[0.07013935 0.21789677 0.40897754 0.10766121 0.41582829 0.05764417]
[0.06800401 0.23409984 0.42994329 0.10637036 0.41563492 0.05737282]
[0.06763827 0.23341264 0.44326798 0.1055347  0.43309007 0.0567678 ]
[0.0674015  0.24072745 0.44986552 0.10491681 0.44417928 0.05666418]
[0.06722643 0.24537328 0.46062096 0.10476164 0.44961212 0.05659709]
[0.06718246 0.24763264 0.46683491 0.10465502 0.45871028 0.05654749]
[0.06715225 0.2514869  0.47259187 0.1046004  0.46396193 0.05653503]
[0.06713678 0.25371029 0.47808446 0.10458125 0.46883987 0.05652647]
[0.06713135 0.25577903 0.48204204 0.10456959 0.47350315 0.05652209]
[0.06712805 0.25775939 0.48577906 0.10456432 0.47686379 0.05652055]
[0.06712656 0.25918672 0.48888915 0.10456208 0.4

# action2

In [22]:
import jieba
import jieba.analyse
import jieba.posseg as pseg

In [17]:
with open('G:/project_courseware/核心班BI/lesson10/L10/textrank/news_高考.txt',encoding ='utf-8' ) as file:
    data = file.read()

In [18]:
data

'7月23日，在万般期待中，各地2020年高考录取分数线陆续公布，拿到分数后的考生们可谓有人欢喜有人愁。安徽省当天也公布了录取分数线，其中文理科一本分数线分别为541分和515分，二本分数线分别为499分和435分。那么被称为亚洲最大的“高考工厂”毛坦厂中学高考成绩怎样？图为毛坦厂中学教室午休的考生。\n7月23日，毛坦厂中学所在的安徽六安市毛坦厂镇官方发布喜报称，根据网络查询，六安市毛坦厂中学、金安高级中学、金安中学补习班2020年高考再创佳绩，再传捷报，安徽籍考生（不含外省考生）本科达线人数10176人，其中600分以上600分以上290人，理科最高分674分，文科最高分608分。也就是在2020年高考中，高考镇有1万多人达到本科线，听起来多少有点让人吃惊，这个数字还不包括其他十几个省份在毛坦厂复读的数百名考生。图为高考镇放学盛大的场面。今年的高考很特殊，因为疫情课业停摆两个多月，随后高考推迟一个月才考试，而就在考试进行时，安徽歙县因为洪水语文和数学被延期考试，湖北黄梅的考生硬是蹚水去考场，而云南一地的考生，考试时还发生了地震。图为高考前，高考镇的卡点。毛坦厂镇因为高考而驰名，被称为“亚洲最大的高考工厂”，外媒曾称该镇是一座偏僻的单一产业城镇，出产的是应试机器，就像其他一些专门生产袜子或圣诞饰品的中国乡镇一样心无旁骛。毛坦厂镇今年参加高考的考生人数超过1.7万人，涉及全国十多个省份。图为考生在上晚自习。\n据悉，毛坦厂镇面积只有3.5平方公里，人口不过万余人，从1999年后，毛坦厂中学借高考复读声名鹊起，每年都要吸引2万多学生和1万多陪读家长，整个小镇接近5万人。租房、生活、学习，众多学生和家长的到来，小镇的经济都围绕着“高考”在转。图为每天早晨，陪读家长在洗衣。在高考前，为了保障高考的顺利进行，高考镇实行了史上最严的“封锁”，在疫情开始之初，通往毛坦厂镇的所有道路都被切断，4月初，安徽省境内高三年级开始复课之后，因为外来复读学生较多，毛坦厂镇曾经短暂对外地家长和考生开放了几天，随之又实行严格管控，一直到7月5日考生离开高考镇时才解封。图为高考前，考生进入学校测量体温。也正是如此，今年的高考镇比往年低调了很多，连往年最热闹的送考节也没有举行，而是和其他所有普通学校一样，用几辆大巴将考生送到市区考试。图为往年的送考节。和衡水中学不一样，到高考镇来学习的都是普通考生

In [26]:
seg_list = jieba.cut(data,cut_all=False)
print(' '.join(seg_list))

Building prefix dict from the default dictionary ...
Loading model from cache C:\Users\ADMINI~1\AppData\Local\Temp\jieba.cache
Loading model cost 0.634 seconds.
Prefix dict has been built successfully.


7 月 23 日 ， 在 万般 期待 中 ， 各地 2020 年 高考 录取 分数线 陆续 公布 ， 拿到 分数 后 的 考生 们 可谓 有人 欢喜 有人 愁 。 安徽省 当天 也 公布 了 录取 分数线 ， 其中 文理科 一本 分数线 分别 为 541 分 和 515 分 ， 二本 分数线 分别 为 499 分 和 435 分 。 那么 被 称为 亚洲 最大 的 “ 高考 工厂 ” 毛坦厂 中学 高考 成绩 怎样 ？ 图为 毛坦厂 中学 教室 午休 的 考生 。 
 7 月 23 日 ， 毛坦厂 中学 所在 的 安徽 六安市 毛坦厂 镇 官方 发布 喜报 称 ， 根据 网络 查询 ， 六安市 毛坦厂 中学 、 金安 高级中学 、 金安 中学 补习班 2020 年 高考 再创 佳绩 ， 再 传捷报 ， 安徽 籍 考生 （ 不 含 外省 考生 ） 本科 达线 人数 10176 人 ， 其中 600 分 以上 600 分 以上 290 人 ， 理科 最高分 674 分 ， 文科 最高分 608 分 。 也 就是 在 2020 年 高考 中 ， 高考 镇有 1 万多 人 达到 本科 线 ， 听 起来 多少 有点 让 人 吃惊 ， 这个 数字 还 不 包括 其他 十几个 省份 在 毛坦厂 复读 的 数百名 考生 。 图为 高考 镇 放学 盛大 的 场面 。 今年 的 高考 很 特殊 ， 因为 疫情 课业 停摆 两个 多月 ， 随后 高考 推迟 一个月 才 考试 ， 而 就 在 考试 进行 时 ， 安徽 歙县 因为 洪水 语文 和 数学 被 延期 考试 ， 湖北 黄梅 的 考生 硬是 蹚 水去 考场 ， 而 云南 一地 的 考生 ， 考试 时 还 发生 了 地震 。 图为 高考 前 ， 高考 镇 的 卡点 。 毛坦厂 镇 因为 高考 而 驰名 ， 被 称为 “ 亚洲 最大 的 高考 工厂 ” ， 外媒 曾 称 该镇 是 一座 偏僻 的 单一 产业 城镇 ， 出产 的 是 应试 机器 ， 就 像 其他 一些 专门 生产 袜子 或 圣诞 饰品 的 中国 乡镇 一样 心无旁骛 。 毛坦厂 镇 今年 参加 高考 的 考生 人数 超过 1.7 万人 ， 涉及 全国 十多个 省份 。 图为 考生 在 上 晚自习 。 
 据悉 ， 毛坦厂 镇 面积 只有 3.5 平方公里 ， 人口 不过 

In [27]:
words = pseg.cut(data)
for word,flag in words:
    print('%s, %s' %(word ,flag))

7, m
月, m
23, m
日, m
，, x
在, p
万般, a
期待, v
中, f
，, x
各地, r
2020, m
年, m
高考, v
录取, v
分数线, n
陆续, d
公布, v
，, x
拿到, v
分数, n
后, f
的, uj
考生, v
们, k
可谓, v
有人, r
欢喜, v
有人, r
愁, v
。, x
安徽省, ns
当天, t
也, d
公布, v
了, ul
录取, v
分数线, n
，, x
其中, r
文理科, n
一本, m
分数线, n
分别, d
为, p
541, m
分, q
和, c
515, m
分, v
，, x
二本, ns
分数线, n
分别, d
为, p
499, m
分, q
和, c
435, m
分, v
。, x
那么, r
被, p
称为, v
亚洲, ns
最大, a
的, uj
“, x
高考, v
工厂, n
”, x
毛, nr
坦厂, n
中学, n
高考, v
成绩, n
怎样, r
？, x
图, n
为, p
毛, nr
坦厂, n
中学, n
教室, n
午休, ns
的, uj
考生, v
。, x

, x
7, m
月, m
23, m
日, m
，, x
毛, nr
坦厂, n
中学, n
所在, b
的, uj
安徽, ns
六安市, ns
毛坦, nr
厂镇, n
官方, n
发布, v
喜报, v
称, v
，, x
根据, p
网络, n
查询, v
，, x
六安市, ns
毛, nr
坦厂, n
中学, n
、, x
金安, nz
高级中学, nt
、, x
金安, nz
中学, n
补习班, n
2020, m
年, m
高考, v
再创, v
佳绩, n
，, x
再, d
传捷报, n
，, x
安徽, ns
籍, ng
考生, v
（, x
不, d
含, v
外省, n
考生, v
）, x
本科, r
达, v
线, n
人数, n
10176, m
人, n
，, x
其中, r
600, m
分, v
以上, f
600, m
分, v
以上, f
290, m
人, n
，, x
理科, n
最高分, l
674, m
分, v
，, x
文科, nz
最高分, l
608, m
分, v
。, x
也, d
就是, d


In [28]:
# 通过TF-IDF获取关键词
keywords = jieba.analyse.extract_tags(data, topK=20, withWeight=True, allowPOS=('n','nr','ns'))
for item in keywords:
    print(item[0],item[1])
print('-'*100)

坦厂 0.652078227430909
毛坦 0.652078227430909
厂镇 0.652078227430909
中学 0.45686148780300007
分数线 0.3884291573490909
家长 0.2753075180527273
六安市 0.20122662378
安徽 0.18529285947954544
小镇 0.15733915599672726
学生 0.15718041332509092
安徽省 0.1474120735198182
疫情 0.14702812945727273
省份 0.1463882340369091
人数 0.11638644293418182
工厂 0.114623369962
二本 0.11376712082636363
传捷报 0.11376712082636363
课业 0.11008107438818182
卡点 0.10867970457181818
外媒 0.10867970457181818
----------------------------------------------------------------------------------------------------


In [29]:
keywords = jieba.analyse.textrank(data, topK=20, withWeight=True, allowPOS=('n', 'ns')) 